apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: staging-ingress
  namespace: staging # build
spec:
  podSelector:
    matchLabels:
      app: service-a # build
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            env: production
  egress:
  - {}

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: production
  namespace: production # build
spec:
  podSelector:
    matchLabels:
      app: service-c # build
  egress:
  - {}
  ingress:
  - {}