---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-c
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-c
  template:
    metadata:
      labels:
        app: service-c
    spec:
      containers:
      - name: service-c
        image: busybox:1.33.1
        command: ["nc", "-lkv", "-p", "8080", "-e", "/bin/sh"]
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service-c
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: service-c
  ports:
  - port: 8080